### ISSUE TITLE
prod scale error

### ISSUE THREAD

**Issue by krpaulson27** [ihmeuw/demUtils#26]
Error on this sample call:

```library(demUtils)

pnn_start <- 0.07671233  # pnn: 1 month - 1 year
pna_start <- pnn_start # pna: 1 month - 6 months
pnb_start <- 0.50136986 # 6 months - 1 year
pna_end <- pnb_start

# in order: pnn, 1-4, 2-4, 1, pna, pnb
dt <- data.table::data.table(
  location_id = 7,
  sex_id = 1,
  year_id = 1,
  draw = 0,
  qx = c(0.027, 0.014, 0.0051, 0.0044, 0.0072, 0.008),
  age_start = c(pnn_start, 1, 2, 1, pna_start, pnb_start),
  age_end = c(1, 5, 5, 2, pna_end, 1)
)

# scale pna & pnb to pnn; 1 and 2-4 to 1-4
scaled <- demUtils::scale(
  dt,
  id_cols = c("age_start", "age_end", "location_id", "sex_id",
              "year_id", "draw"),
  value_cols = c("qx"),
  col_stem = "age",
  col_type = "interval",
  mapping = data.table(age_start = c(0.07671233, 1),
                       age_end = c(1, 5)),
  agg_function = prod
)

Error: `name` must be a character vector formatted in
                          left-closed, right-open interval notation as described
                          in `gen_name()`

**Comment by krpaulson27** [comment]
I think this is an integer age issue. This example works when I modify the age groups to have age_start and age_end as integer values.

Another note: this function gives me an error/warning/message/etc about missing data for missing the overall aggregate, (in this example, would be 0.0767 - 5). I'm not sure why you would need aggregates not specified in `mapping`.

**Comment by chacalle** [comment]
Oh I see your other comment now. The mapping when scaling interval variables is determined from the data as described here. https://github.com/ihmeuw/demUtils/blob/master/R/agg_scale.R#L23-L25. I should add a warning or error if a mapping is provided when scaling interval variables.

The example input data you provided is
```
> dt[order(age_start, age_end)]
   location_id sex_id year_id draw     qx  age_start   age_end
1:           7      1       1    0 0.0072 0.07671233 0.5013699
2:           7      1       1    0 0.0270 0.07671233 1.0000000
3:           7      1       1    0 0.0080 0.50136986 1.0000000
4:           7      1       1    0 0.0044 1.00000000 2.0000000
5:           7      1       1    0 0.0140 1.00000000 5.0000000
6:           7      1       1    0 0.0051 2.00000000 5.0000000
```

And this is the interval tree that is inferred from the available data. All the nodes are in the dataset except for the root, I can add an exception for the root since it is included regardless of what is available in the data
```
> tree
                         levelName
1 [0.07671233, 5)                 
2  ¦--[0.07671233, 1)             
3  ¦   ¦--[0.07671233, 0.50136986)
4  ¦   °--[0.50136986, 1)         
5  °--[1, 5)                      
6      ¦--[1, 2)                  
7      °--[2, 5)
```

**Comment by chacalle** [comment]
Ok @krpaulson27 now this should work if you remove the `mapping` argument from the original call

**Comment by krpaulson27** [comment]
Thanks for your help in fixing this! The solutions you implemented look good to me.
